home/urls.py
from home.views import Login, Logout, index
from django.conf.urls import url
from django.urls import path

app_name = 'home'


urlpatterns = [


    url(r'^$', index, name='index'),

]

jpsiteapi/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from django.urls import path
from django.conf.urls.static import static
from django.views.static import serve
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from customer.views import CustomerCreateView, CustomerDetailView
from orders.views import OrderCreateView, OrderDetailView, OrderExpenseCreateView, OrderExpenseRUD, OrdersDestroyView, \
                         SweaterSizeCreateView
from factory.views import FactoryCreateView, FactoryDetailView, FactoryContacListtCreateView, FactoryContactDetailView
from inventory.views import InventoryListCreateView, SpecListCreateView,InventoryDetailView, \
                            SpecDetailView, InventoryListView

from orders.views import OrdersTest, OrderTaskView, OrderTaskRUD, OrderListFilterView, TaskDashBoardView, OrderChartView
from todos.views import TodoCreateView, TodoGroupCreateView,TodosRUD, TodoGroupCreateRUDView, \
    TodosGroupViewSet
from home.views import index

from jpsiteapi.settings import MEDIA_URL, MEDIA_ROOT


from django.urls import path, re_path


urlpatterns = [

    path('grappelli/', include('grappelli.urls')),  # grappelli URLS

    
    path('api/admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$',
        serve,
        {'document_root': MEDIA_ROOT}),

    url(r'',
        include('home.urls',
                namespace='home')),

    url(r'api/api-token-auth/', obtain_jwt_token),
    url(r'api/api-token-refresh/', refresh_jwt_token),
    url(r'api/api-token-verify/', verify_jwt_token),


    path('api/task/',
         TodoCreateView.as_view(),
         name='todos'
         ),
    path('api/task/<int:pk>/',
         TodosRUD.as_view(),
         name='todos-RUD'
         ),
    path('api/task/group/',
         TodoGroupCreateView.as_view(),
         name='todos-create'
         ),
    path('api/task/group/filter/',
         TodosGroupViewSet.as_view({'get': 'list'}),
         name='todos-group-filter'),

    path('api/task/group/<int:pk>/',
         TodoGroupCreateRUDView.as_view(),
         name='todosgroup-detail'
         ),
    path('api/factory/',
         FactoryCreateView.as_view(),
         name='factory-list'),
    path('api/factory/<int:pk>/',
         FactoryDetailView.as_view(),
         name='factory-detail'),
    path('api/factory/contacts/',
         FactoryContacListtCreateView.as_view(),
         name='factory-contact-list'
         ),
    path('api/factory/contacts/<int:pk>/',
         FactoryContactDetailView.as_view(),
         name='factory-contact-list'
         ),


    path('api/customer/',
         CustomerCreateView.as_view(),
         name='customer-list'),
    path('api/customer/<int:pk>/',
         CustomerDetailView.as_view(),
         name='customer-detail'),

    path('api/myorders/',
         OrdersTest.as_view(),
         name='orders-test'),
    path('api/orders/',
         OrderCreateView.as_view(),
         name='order-list'),
    path('api/orders/paginator/',
         OrderListFilterView.as_view({'get': 'list'}),
         name='order-list-filter'),
    path('api/orders/delete/<int:pk>/',
         OrdersDestroyView.as_view(), name='delete-orders'),
    path('api/orders/<int:pk>/',
         OrderDetailView.as_view(),
         name='order-detail'),
    path('api/orders/tasks/',
         OrderTaskView.as_view(),
         name='list-order-task'
         ),
    path('api/orders/tasks/<int:pk>',
         OrderTaskRUD.as_view(),
         name='list-order-task'
         ),

    path('api/order-expense/',
         OrderExpenseCreateView.as_view(),
         name='order-expense'),
    path('api/order-expense/<int:pk>/',
         OrderExpenseRUD.as_view(),
         name='order-epxense-rud'),
    path('api/sweater-sizes/',
         SweaterSizeCreateView.as_view(), name='sweater-sizes'),

    path('api/inventory/',
         InventoryListCreateView.as_view(),
         name='inventory-create'),
    path('api/inventorylist/',
         InventoryListView.as_view(),
         name='inventory-list'),
    path('api/inventory/<int:pk>/',
         InventoryDetailView.as_view(),
         name='inventory-detail'),

    path('api/inventory/specs/',
         SpecListCreateView.as_view(),
         name='spec-list'),
    path('api/inventory/specs/<int:pk>/',
         SpecDetailView.as_view(),
         name='inventory-detail'),

    path('api/dashboard/',
         TaskDashBoardView.as_view(),
         name='dashboard'
         ),

    url(r'$', index),
    path('api/orders-chart/',
         OrderChartView.as_view(),
         name='order-chart'),

  


]

static(MEDIA_URL, document_root=MEDIA_ROOT)


"""
useful regex urls
pk (?P<pk>\d+)
slug : (?P<slug>[-\w]+)
slug + pk (?P<slug>[-\w]+)-(?P<pk>\d+)
(?P<username>[\w.@+-]+)

dates = (?P<year>[0-9]{4})
year mont  = (?P<year>[0-9]{4})/(?P<month>[0-9]{2})
ymd (?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})


"""
#from django.http import HttpResponse, request
"""
import datetime

now = datetime.date.today()

def hello(request):
    return HttpResponse("Hello World")

def today(request):
    return HttpResponse(now)
    
def current_date(request):
    import datetime
    now = datetime.datetime.now()
    html = "<html><body> It is now %s. </body></html>" % now
    return HttpResponse(html)
    



    path('api/task/',
         TaskCreateView.as_view(),
         name='task-list'),
    path('api/task/<int:pk>/',
         TaskDetailView.as_view(),
         name='task-detail'),

"""

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms #forms.Forms
from django.forms import ModelForm

home/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView


class Login(LoginView):

    template_name = 'login.html'
    success_url = 'index.html'

class Logout(LogoutView):

    success_url = 'index.html'


def index(request):
    return render(request, 'index.html')
"""

# Create your views here.
@api_view(['POST'])
@permission_classes([AllowAny, ])
def authenticate_user(request):
    try:
        email = request.data['email']
        password = request.data['password']

        user = User.objects.get(email=email, password=password)
        if user:
            try:
                payload = jwt_payload_handler(user)
                token = jwt.encode(payload, settings.SECRET_KEY)
                user_details = {}
                user_details['name'] = "%s %s" % (
                    user.first_name, user.last_name)
                user_details['token'] = token
                user_logged_in.send(sender=user.__class__,
                                    request=request, user=user)
                return Response(user_details, status=status.HTTP_200_OK)

            except Exception as e:
                raise e
        else:
            res = {
                'error': 'can not authenticate with the given credentials or the account has been deactivated'}
            return Response(res, status=status.HTTP_403_FORBIDDEN)
    except KeyError:
        res = {'error': 'please provide a email and a password'}
        return Response(res)
        
        
        
2
user_logged_in.send(sender=user.__class__,
                                    request=request, user=user)
                                    
                                    class UserRetrieveUpdateAPIView(RetrieveUpdateAPIView):
 
    # Allow only authenticated users to access this url
    permission_classes = (IsAuthenticated,)
    serializer_class = UserSerializer
 
    def get(self, request, *args, **kwargs):
        # serializer to handle turning our `User` object into something that
        # can be JSONified and sent to the client.
        serializer = self.serializer_class(request.user)
 
        return Response(serializer.data, status=status.HTTP_200_OK)
 
    def put(self, request, *args, **kwargs):
        serializer_data = request.data.get('user', {})
 
        serializer = UserSerializer(
            request.user, data=serializer_data, partial=True
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
 
        return Response(serializer.data, status=status.HTTP_200_OK)
"""

home/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
    <!doctype html>
    <html lang="en">
    <head>
        <title>Front End</title>
        <meta content='Angular example app is a base project to start coding with Angular' name='description'>
        <meta charset="utf-8">
    
        <base href="/">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="canonical" href="http://angularexampleapp.com/">
        <link rel="icon" type="image/x-icon" href="favicon.ico">
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
        <link href="https://unpkg.com/bootstrap-css-only@4.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://unpkg.com/font-awesome@4.7.0/css/font-awesome.css" rel="stylesheet">
        <link href="https://unpkg.com/angular-calendar@0.26.4/css/angular-calendar.css" rel="stylesheet">
        <link href="https://unpkg.com/flatpickr@4.5.2/dist/flatpickr.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'styles.css' %}">

        
    </head>
    <body>
    <base href="/">
 {% block content %} {% endblock content %}
</body>
</html>

home/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

 {% block content %} 

{% verbatim %}

  <app-root></app-root>
{% endverbatim %}
            {% block js %}
    <script  src="{% static 'main.js' %}"></script>
    <script  src="{% static 'polyfills.js' %}"></script>
    <script  src="{% static 'runtime.js' %}"></script>
    <script  src="https://ajax.googleapis.com/ajax/libs/hammerjs/2.0.8/hammer.min.js"></script>
            {% endblock js %}
{% endblock content %}

home/templates/login.html
{% extends 'base.html' %}


{% block content %}


    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="Login">Log In</button>

        <input type="hidden" name="next" value="{% url 'home:index' %}"/>
    </form>

{% endblock %}